# -*- conding: utf-8 -*-

"""
INTRODUCTION
------------
Programme de création/verification de fichiers HTML5
et CSS balisés.

Créateur: Alexandre BONIN 2016
PYTHON
"""

from tkinter import Tk, Toplevel, Button, Label


class Application(object):
    
    def __init__(self):
        self.master = Tk()
        
        message_base = ("Bonjour, HTML Creator vous permet de créer "
        "des fichiers HTML5 et CSS 3 balisés et fonctionnels en un seul "
        "clic ! Vous voulez essayer ? Cliquez donc sur le bouton ci-dessous")
        
        
        self.description = Label(master=self.master,
                                 text=message_base,
                                 font="Times 9")
        self.description.grid(row=0, column=0, pady=15)
        
        self.button_html = Button(master=self.master,
                                  text="Créer fichier HTML & CSS",
                                  font="Georgia 8",
                                  command=self.creer_fichiers)
        self.button_html.grid(row=1, column=0)
                             
                             
    def creer_fichiers(self):
        self.creer_fichier_html()
        self.creer_fichier_css()
    
    def creer_fichier_html(self):
        fichier = open(file="page.html", mode="w+")
        
        contenu = ('<!DOCTYPE html>\n<!-- Generated by HTML Creator (2016) -->\n'
        '<html>\n'
        '   <head>\n'
        '       <meta charset="UTF-8"/>\n'
        '       <link rel="Stylesheets" href="style.css"/>\n'
        '       <title>Titre Page</title>\n'
        '   </head>\n\n'
        '   <body>\n'
        '       <header>\n        </header>\n\n'
        '       <section>\n        </section>\n\n'
        '       <footer>\n        </footer>\n\n'
        '   </body>\n'
        '</html>')
        
        fichier.write(contenu)
        fichier.close()
        
    def creer_fichier_css(self):
    
        fichier = open(file="style.css", mode="w+")
        
        contenu = ("/* CSS generated by HTML Creator (2016) */\n\n"
        "@font-face\n{\n}\n" "body\n{\n}")
        
        fichier.write(contenu)
        fichier.close()
                             
def main():
    app = Application()
    app.master.mainloop()

main()


if __name__ == "__main__":
    pass
    